Feature: Create generating invitation link fn
nishiki-tech/nishiki-frontend pull request #245
Opened 2024-02-20 22:43 UTC by ShoeheyOt

## Overview

implement fetching hash value

## Screen Captures

[invHash_test.webm](https://github.com/nishiki-tech/nishiki-frontend/assets/142355969/4f70ac37-e754-40f6-adb7-b84c04182b17)

## References

- https://dev.to/hirohata/created-result-type-in-typescript-128m
- https://jestjs.io/docs/expect

## Notes

-

## Assignee Checklist:

- [X] The naming convention of the PR title is correct (See the comment at the top of this template)
- [X] The base branch is correct (See: [Types of Branches](https://github.com/nishiki-tech/nishiki-frontend/blob/develop/docs/CONTRIBUTING.md#types-of-branches))
- [X] The branch name follows the [Branch Naming Conventions](https://github.com/nishiki-tech/nishiki-frontend/blob/develop/docs/CONTRIBUTING.md#branch-naming-conventions)
- [X] The correct assignees and reviewers have been designated for this PR
- [X] The coding style follows the [Coding Style Guide](https://github.com/nishiki-tech/nishiki-frontend/blob/develop/docs/STYLEGUIDE.md)
- [X] All the related issues are associated with this PR
- [X] All criteria in the associated issues are met (please tick the checkboxes)
- [X] My changes do not generate new warnings or errors (especially in the console)

## Reviewer Checklist:

- [ ] Double-check the "Assignee Checklist"
- [ ] The code follows the generic best practices and our [Coding Style Guide](https://github.com/nishiki-tech/nishiki-frontend/blob/develop/docs/STYLEGUIDE.md)
- [ ] The code is well-commented and easy to understand
- [ ] The UI changes accurately reflect the provided design

2024-02-21 06:32 UTC, nick-y-ito requested changes
@ShoeheyOt 
Thank you for your work! Please take a look at the comments below and address those issues :)

2024-02-21 06:32 UTC, nick-y-ito commented on src/features/groups/components/InviteMemberDialog/InviteMemberDialogContent.tsx
> +const BACKEND_API_DOMAIN = process.env.NEXT_PUBLIC_BACKEND_API_DOMAIN || '';
Please add a line break before each function declaration. If it has a comment block, then the line break should be right before the comment.

2024-02-21 06:32 UTC, nick-y-ito commented on src/features/groups/components/InviteMemberDialog/InviteMemberDialogContent.tsx
> +  groupId,
`@param` for groupId is missing

2024-02-21 06:32 UTC, nick-y-ito commented on src/components/page/MembersPage.tsx
> +export const MembersPage: React.FC<IMembersPageProps> = async ({ id }) => {
Please avoid using wildcard imports.
See: https://github.com/nishiki-tech/nishiki-frontend/blob/develop/docs/STYLEGUIDE.md#avoid-using-wildcard-imports

2024-02-21 06:32 UTC, nick-y-ito commented on src/lib/api/group/client/groupApiClient.client.ts
> +): Promise<Result<string, string>> => {
Currently, it is not very clear what the type `string` refers to for the return type:
```ts
Result<string, string>
```

I suggest creating an interface for the return value and changing the return type like so:
```ts
interface IPutgenerateInvitationLinkHashResponse {
  hash: string
  // This structure allows to add more values for the future
  // It's also kind of a convention to always make the return value an object
}
:
Promise<Result<IPutgenerateInvitationLinkHashResponse, string>>
```

2024-02-21 06:32 UTC, nick-y-ito commented on src/lib/api/group/client/groupApiClient.client.ts
> +export const generateInvitationLinkHash = async (
As per convention, please rename it to start with `put` (one of the request methods).

2024-02-21 16:01 UTC, kotaaaa commented
[This button](https://github.com/nishiki-tech/nishiki-frontend/blob/develop/src/features/groups/components/MemberList.tsx#L14-L16) at GroupSingle page should have same functionality of [InviteMemberDialogContent.tsx](https://github.com/nishiki-tech/nishiki-frontend/pull/245/files#diff-989ac945aae3710b341f62402e478ce243d3c632b0135823e1046fb4d7270e86).

2024-02-23 17:51 UTC, kotaaaa approved these changes

2024-02-24 04:06 UTC, nick-y-ito approved these changes
@ShoeheyOt
Thank you for fixing them! I think it's good to go 😄

2024-02-24 04:12 UTC, merged