Feat: Implement food DELETE functionality
nishiki-tech/nishiki-frontend pull request #246
Opened 2024-02-21 18:35 UTC by nick-y-ito

## Overview

This PR implements the food DELETE functionality.

## Changes

-

## Review points

-

## Screen Captures

## References

-

## Notes

-

## Assignee Checklist:

- [ ] The naming convention of the PR title is correct (See the comment at the top of this template)
- [ ] The base branch is correct (See: [Types of Branches](https://github.com/nishiki-tech/nishiki-frontend/blob/develop/docs/CONTRIBUTING.md#types-of-branches))
- [ ] The branch name follows the [Branch Naming Conventions](https://github.com/nishiki-tech/nishiki-frontend/blob/develop/docs/CONTRIBUTING.md#branch-naming-conventions)
- [ ] The correct assignees and reviewers have been designated for this PR
- [ ] The coding style follows the [Coding Style Guide](https://github.com/nishiki-tech/nishiki-frontend/blob/develop/docs/STYLEGUIDE.md)
- [ ] All the related issues are associated with this PR
- [ ] All criteria in the associated issues are met (please tick the checkboxes)
- [ ] My changes do not generate new warnings or errors (especially in the console)

## Reviewer Checklist:

- [ ] Double-check the "Assignee Checklist"
- [ ] The code follows the generic best practices and our [Coding Style Guide](https://github.com/nishiki-tech/nishiki-frontend/blob/develop/docs/STYLEGUIDE.md)
- [ ] The code is well-commented and easy to understand
- [ ] The UI changes accurately reflect the provided design

2024-02-23 06:13 UTC, kanta1207 commented on src/features/foods/components/FoodCardList/FoodCardDropdownMenu.tsx
It's a minor point, but considering the existing codebase, it would be more consistent to name this file `FoodCardDropdownMenuTriggerButton` and to create `FoodCardDropdownMenuContent` component separately.

2024-02-23 07:16 UTC, kanta1207 requested changes
Thank you for the work! I really liked your approach on solving the conflict between `Dialog` and `DropdownMenu`, I'll follow it in my branch with the issue #248.

I just left some comments & questions, please kindly take a look at them!

2024-02-23 07:16 UTC, kanta1207 commented on src/features/foods/components/DeleteFoodDialogContent.tsx
Basically, I really liked your approach to this PR overall!
However I have some concerns & questions, especially on this file.

1. Since this component will not open the parent component, should we avoid passing `setIsParentOpen` function and just pass a function to close the parent, with naming like `handleCloseParent`?
2. Same for `setIsDialogOpen`. Is it better to limit the function to just close the dialog, with naming like `handleCloseDialog`? 
3. Could you share with me the purpose of prop `closeParentOnCancel` a bit more? If this component is only used for deleting the food from dropdownMenu, it seems like unnecessary because it will always have to close the dropdownMenu on cancel button click.
 Just checking if `setIsParentOpen` prop is undefined or not might be good enough?

2024-02-23 07:16 UTC, kanta1207 commented on src/features/foods/components/DeleteFoodDialogContent.tsx
For the question 1 and 2, what I meant is,
defining a function like this ⬇️ in parent component and pass it to this component.
```ts
const handleCloseDialog = () => setIsDialogOpen(false)

```

2024-02-23 19:28 UTC, nick-y-ito commented on src/features/foods/components/DeleteFoodDialogContent.tsx
For questions No. 1  and 2, I agree with your suggestion. That approach is more appropriate and safe.
For No. 3, the reason is that the "parent" should not be closed if the "parent" is the "EditDrawer".

2024-02-23 20:03 UTC, nick-y-ito commented on src/features/foods/components/DeleteFoodDialogContent.tsx
> ```ts
> const handleCloseDialog = () => setIsDialogOpen(false)
> ```

I named those props, like `onDialogClose` instead of `handleXxxYyy` since the functions like `setIsDialogOpen(false)` are not event handlers, but **just functions that should be called within an event handler**.

2024-02-24 05:26 UTC, kanta1207 approved these changes
Thank you for fixing the points that I mentioned, and also addressing some points that I didn't even realized! 

It all looks good to me 👍

2024-02-24 05:26 UTC, kanta1207 commented on src/features/foods/components/FoodCardList/FoodCardDropdownMenu.tsx
> +   * The function that is called when the dropdown menu item is selected.
Didn't even realize the bug! Thank you for fixing it so promptly !

2024-02-24 05:30 UTC, nick-y-ito commented on src/features/foods/components/FoodCardList/FoodCardDropdownMenu.tsx
After our discussion, we concluded that naming should depend on the situation without stringent conventions.

2024-02-24 05:31 UTC, merged