Feature: create container feature(UI) in group single page
nishiki-tech/nishiki-frontend pull request #256
Opened 2024-02-24 02:42 UTC by ShoeheyOt

## Overview

implement displaying a drawer for creating container when plus icon touched, only UI part.

## Changes

-

## Review points

-

## Screen Captures
[createContainerDrawerUI.webm](https://github.com/nishiki-tech/nishiki-frontend/assets/142355969/b428978b-7721-4a29-847f-51c10fe7b6e4)

## References

-

## Notes

-

## Assignee Checklist:

- [X] The naming convention of the PR title is correct (See the comment at the top of this template)
- [X] The base branch is correct (See: [Types of Branches](https://github.com/nishiki-tech/nishiki-frontend/blob/develop/docs/CONTRIBUTING.md#types-of-branches))
- [X] The branch name follows the [Branch Naming Conventions](https://github.com/nishiki-tech/nishiki-frontend/blob/develop/docs/CONTRIBUTING.md#branch-naming-conventions)
- [X] The correct assignees and reviewers have been designated for this PR
- [X] The coding style follows the [Coding Style Guide](https://github.com/nishiki-tech/nishiki-frontend/blob/develop/docs/STYLEGUIDE.md)
- [X] All the related issues are associated with this PR
- [X] All criteria in the associated issues are met (please tick the checkboxes)
- [X] My changes do not generate new warnings or errors (especially in the console)

## Reviewer Checklist:

- [ ] Double-check the "Assignee Checklist"
- [ ] The code follows the generic best practices and our [Coding Style Guide](https://github.com/nishiki-tech/nishiki-frontend/blob/develop/docs/STYLEGUIDE.md)
- [ ] The code is well-commented and easy to understand
- [ ] The UI changes accurately reflect the provided design

2024-02-24 05:08 UTC, nick-y-ito requested changes
@ShoeheyOt 
Thank you for your implementation! Although I left many comments, they are all acceptable, and the appearance and the behavior look very good. Great job!! Please kindly take a look at the comments.

However, I would like you to give the "Assignee's Checklist" your full attention. Three of them do not meet the conditions.

- [ ] The branch name follows the [Branch Naming Conventions](https://github.com/nishiki-tech/nishiki-frontend/blob/develop/docs/CONTRIBUTING.md#branch-naming-conventions)
- [ ] All the related issues are associated with this PR
- [ ] All criteria in the associated issues are met (please tick the checkboxes)

2024-02-24 05:08 UTC, nick-y-ito commented on src/features/groups/components/ContainerList/CreateContainerButton/CreateContainerBottomDrawerContent.tsx
> +}
Could you please also add TSDoc to each property of this interface? There are many existing interfaces that still do not have TSDoc, though. It's a best practice to always add TSDocs to interfaces, as well as functions.

You can get an idea by visiting the `src/components/layouts/MobileLayout.tsx` file.
Also this PR (https://github.com/nishiki-tech/nishiki-frontend/pull/246/files) includes a lot of TSDocs for interfaces.

2024-02-24 15:27 UTC, ShoeheyOt commented on src/features/groups/components/ContainerList/CreateContainerButton/CreateContainerBottomDrawerContent.tsx
> +            ></FormField>
@nick-y-ito Thank you for reviewing!
I have changed it to self-closing, can I change it for other file too? same things happens in below file
src/features/groups/components/CreateGroupButton/CreateGroupDrawerContent.tsx

2024-02-24 15:41 UTC, ShoeheyOt commented on src/features/groups/components/ContainerList/CreateContainerButton/CreateContainerBottomDrawerContent.tsx
> +}) => {
@nick-y-ito Thanks you for reviewing!
can I change below file as well? src/features/groups/components/CreateGroupButton/CreateGroupDrawerContent.tsx

2024-02-24 16:12 UTC, nick-y-ito commented on src/features/groups/components/ContainerList/CreateContainerButton/CreateContainerBottomDrawerContent.tsx
> +            ></FormField>
Sure! We would rather appreciate it 😁 
Please leave a comment if you make a change that is not related to the primary task.

2024-02-24 16:12 UTC, nick-y-ito commented on src/features/groups/components/ContainerList/CreateContainerButton/CreateContainerBottomDrawerContent.tsx
> +}) => {
Sure! We would rather appreciate it 😁 
Please leave a comment if you make a change that is not related to the primary task.

2024-02-25 05:30 UTC, nick-y-ito approved these changes
@ShoeheyOt 
Thank you for fixing all the points I commented on earlier!
Now, this PR looks good to go 😄

2024-02-25 05:36 UTC, merged