Feature/273 implement delete group api client
nishiki-tech/nishiki-frontend pull request #282
Opened 2024-02-28 17:17 UTC by kanta1207

## Overview

## Changes

-

## Review points

-

## Screen Captures

## References

-

## Notes

-

## Assignee Checklist:

- [ ] The naming convention of the PR title is correct (See the comment at the top of this template)
- [ ] The base branch is correct (See: [Types of Branches](https://github.com/nishiki-tech/nishiki-frontend/blob/develop/docs/CONTRIBUTING.md#types-of-branches))
- [ ] The branch name follows the [Branch Naming Conventions](https://github.com/nishiki-tech/nishiki-frontend/blob/develop/docs/CONTRIBUTING.md#branch-naming-conventions)
- [ ] The correct assignees and reviewers have been designated for this PR
- [ ] The coding style follows the [Coding Style Guide](https://github.com/nishiki-tech/nishiki-frontend/blob/develop/docs/STYLEGUIDE.md)
- [ ] All the related issues are associated with this PR
- [ ] All criteria in the associated issues are met (please tick the checkboxes)
- [ ] My changes do not generate new warnings or errors (especially in the console)

## Reviewer Checklist:

- [ ] Double-check the "Assignee Checklist"
- [ ] The code follows the generic best practices and our [Coding Style Guide](https://github.com/nishiki-tech/nishiki-frontend/blob/develop/docs/STYLEGUIDE.md)
- [ ] The code is well-commented and easy to understand
- [ ] The UI changes accurately reflect the provided design

2024-02-28 18:05 UTC, kanta1207 commented on src/features/groups/components/GroupCardList/GroupCard/GroupCardContent/GroupCardDropdownMenuTriggerButton/GroupCardDropdownMenuContent/DeleteGroupDialogTriggerButton/index.tsx
This file has changed just because of props drilling.

2024-02-28 18:05 UTC, kanta1207 commented on src/features/groups/components/GroupCardList/GroupCard/GroupCardContent/GroupCardDropdownMenuTriggerButton/GroupCardDropdownMenuContent/index.tsx
This file has changed just because of props drilling of `groupId`.

2024-02-28 18:05 UTC, kanta1207 commented on src/features/groups/components/GroupCardList/GroupCard/GroupCardContent/GroupCardDropdownMenuTriggerButton/index.tsx
This file has changed just because of props drilling of `groupId`.

2024-02-28 18:06 UTC, kanta1207 commented on src/features/groups/components/GroupCardList/GroupCard/GroupCardContent/index.tsx
This file has changed just because of props drilling of `groupId`.

2024-02-28 20:17 UTC, nick-y-ito requested changes
@kanta1207 
Thank you for your review! Overall, I have nothing to say about the implementation :)

I have left comments only for code styling. Please kindly take a look and address them.

2024-02-29 02:28 UTC, kanta1207 commented
@nick-y-ito 
Thank you for your review!

I addressed the points you mentioned following the coding style guide in the latest commit.
Please take a look at them whenever you have a moment 🙏

2024-02-29 03:12 UTC, nick-y-ito requested changes
@kanta1207 
Thank you for the update! I still see the issues that I pointed out. Please take a look.

2024-02-29 03:12 UTC, nick-y-ito commented on src/features/groups/lib/actions.ts
> + * @param groupId - The unique identifier of a group
> this kind of description needs to provide more helpful information.

2024-02-29 03:12 UTC, nick-y-ito commented on src/features/groups/lib/actions.ts
> + * @param groupId - The unique identifier of a group
> this kind of description needs to provide more helpful information.

2024-02-29 05:19 UTC, kanta1207 commented
@nick-y-ito 
Sorry for missing the review points...
I fixed them! Please kindly take a look at them anytime when you're available!

2024-02-29 05:31 UTC, nick-y-ito approved these changes
@kanta1207 
Thank you for the update! LGTM :)

2024-02-29 05:40 UTC, merged